# Generated by Django 6.0 on 2025-12-23 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date when product was first added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='last_sold_date',
            field=models.DateTimeField(blank=True, help_text='Last date this product was sold', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='payment_successful',
            field=models.BooleanField(default=False, help_text='Has this product been successfully sold at least once'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(default=0, help_text='Current stock available'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_sold',
            field=models.IntegerField(default=0, help_text='Total quantity sold'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_price_sold',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue from this product', max_digits=10),
        ),
    ]
