# Generated by Django 6.0 on 2026-03-10 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='The topic this category belongs to (e.g. Video Games)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='store.topic'),
        ),
    ]
