# Generated by Django 6.0 on 2026-01-02 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('PENDING_RETURN', 'Pending Product Return'), ('PRODUCT_RECEIVED', 'Product Received - Processing Refund'), ('PROCESSING_REFUND', 'Processing PayPal Refund'), ('COMPLETED', 'Refund Completed'), ('REJECTED', 'Refund Rejected'), ('CANCELLED', 'Cancelled by Customer')], default='PENDING_RETURN', max_length=30)),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Product is defective'), ('WRONG_ITEM', 'Wrong item received'), ('NOT_AS_DESCRIBED', 'Not as described'), ('CHANGED_MIND', 'Changed my mind'), ('OTHER', 'Other reason')], max_length=30)),
                ('reason_details', models.TextField(blank=True, help_text='Additional details about the refund reason')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rewards_used', models.DecimalField(decimal_places=2, default=0.0, help_text='Rewards points used in original purchase', max_digits=10)),
                ('tracking_number', models.CharField(blank=True, help_text="Customer's return tracking number", max_length=200)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('paypal_refund_id', models.CharField(blank=True, help_text='PayPal refund transaction ID', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_received_at', models.DateTimeField(blank=True, null=True)),
                ('refund_completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='payment.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refund Request',
                'verbose_name_plural': 'Refund Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_refund', models.PositiveIntegerField(help_text='Number of items being returned')),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Refund amount for this item', max_digits=10)),
                ('condition_acceptable', models.BooleanField(default=False, help_text='Product in acceptable condition')),
                ('condition_notes', models.TextField(blank=True, help_text='Notes about product condition')),
                ('restocked', models.BooleanField(default=False, help_text='Product added back to inventory')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.orderitem')),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.refundrequest')),
            ],
            options={
                'verbose_name': 'Refund Item',
                'verbose_name_plural': 'Refund Items',
            },
        ),
    ]
