# Generated by Django 6.0 on 2026-01-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_refundrequest_refunditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount to refund via PayPal (order.amount_paid - what customer actually paid in cash)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='rewards_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Rewards used in original purchase. NOT automatically restored - admin must manually approve via 'Restore rewards as goodwill' action", max_digits=10),
        ),
    ]
