# Generated by Django 6.0 on 2026-04-27 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_refundrequest_refund_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='admin_verified',
            field=models.BooleanField(default=False, help_text="Administrator has reviewed and verified this refund request. REQUIRED before 'Mark as processing PayPal refund' or 'Complete refund' actions can run. Use the 'Verify & approve refund requests' action to set this flag."),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the refund was verified by an admin', null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who verified this refund request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_refunds', to=settings.AUTH_USER_MODEL),
        ),
    ]
